name: Ruby CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
#  workflow_dispatch:
   

jobs:
  InitialActionTest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0 # You can change this to match your project's Ruby version
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    - name: Run tests
      run: bundle exec rspec